### ISSUE TITLE
Update Moodle-Link Methodenkolloquium

### ISSUE THREAD

**Issue by waidschrat** [PHB-Methods/phb-methoden-website#19]
Ich stelle mich zu doof an, den Link für dieses Semester zu aktualisieren. 
Gibt es da einen Trick bzw. verstecken Button @selfawaresoup ?

https://zoom.us/j/98182454829?pwd=AmNaXGbMKnbXOKDIwvSLMISYP8u4me.1

**Comment by selfawaresoup** [comment]
erledigt
